### PR TITLE
When un-setting the mesh anchor, try to use the document's configured anchors

### PR DESCRIPTION
**Pull request by righthandofvecna**
When you have a token on a non-isometric scene which defines an anchor, enabling this module overrides the anchor even on scenes that don't have isometric enabled.

### CODE REVIEW

**Comment by arlosmolten** [comment]
I have a dilemma about whether this anchor variable should be implemented differently, and should have one value for isometric and one for top-down. The way it is now, there will always be problems. I had decided to always leave 0.5/0.5 for top-down, because something different from that is almost never used in normal games.

With this change, if the token needs to have a different anchor value between isometric and top-down, would the player/DM have to keep changing it every time they switch between scenes?

**Comment by righthandofvecna** [comment]
I don't believe so, no. Right now, this module is entirely overwriting the default anchor values in every case in favor of 0.5. It looks like there _was_ code that used flags that this module defined (`isoAnchorX` and `isoAnchorY`) but that code is commented out. Even if it got uncommented, it would still switch which set of variables it was using based on whether the scene is set as isometric.

An example of why the correct anchors are needed:
image

**Comment by arlosmolten** [comment]
My last update was all about adjusting the anchor value for tokens with asymmetric art sizes. The anchor value being set is important for this functionality and in this case it will never be 0.5/0.5. The isoAnchorX and isoAnchorY variables are variables used in `token.js` that store the position of the asymmetric token.

I tried to develop a way to store the original X and Y anchor of the token as a flag so that I could retrieve it when the scene changes, but I didn't succeed, so I left it as is.

**Comment by righthandofvecna** [comment]
That makes sense. I like the dragging preview crosshair you added 😆 

I think I've updated this so the anchors for isometric scenes are separate from the ones for non-isometric scenes

**Comment by arlosmolten** [comment]
Reverts https://github.com/arlosmolten/isometric-perspective/pull/9

These changes breaks the aligment tool. While using, the anchor shouldn't be updated, cause the token will be moving too.

**Comment by arlosmolten** [comment]
test

**Pull request merged**
